config/routes.rb
GiftCardsChallenge::Application.routes.draw do
  resources :gift_cards
  match 'report/gift_cards' => 'reports#gift_cards'

end

app/models/gift_card.rb
class GiftCard
  include Mongoid::Document
  field :sender, type: String
  field :receiver, type: String
  field :description, type: String
  field :value, type: Float

  def self.report

    report = {}

    GiftCard.all.distinct(:sender).each do |sender_name|
      report[sender_name] = {
        :qty_friends => GiftCard.where( sender: sender_name ).distinct( :receiver ).count,
        :gifts_given => GiftCard.where( sender: sender_name ).count,
        :spent       => GiftCard.where( sender: sender_name ).sum( :value )
      }
    end

    report
  end

  def self.amount sender_name, receiver_name
    GiftCard.where( sender: sender_name, receiver: receiver_name ).sum( :value )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gift_cards_controller.rb
class GiftCardsController < ApplicationController
  # GET /gift_cards
  # GET /gift_cards.json
  def index
    @gift_cards = GiftCard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gift_cards }
    end
  end

  # GET /gift_cards/1
  # GET /gift_cards/1.json
  def show
    @gift_card = GiftCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gift_card }
    end
  end

  # GET /gift_cards/new
  # GET /gift_cards/new.json
  def new
    @gift_card = GiftCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gift_card }
    end
  end

  # GET /gift_cards/1/edit
  def edit
    @gift_card = GiftCard.find(params[:id])
  end

  # POST /gift_cards
  # POST /gift_cards.json
  def create
    @gift_card = GiftCard.new(params[:gift_card])

    respond_to do |format|
      if @gift_card.save
        format.html { redirect_to @gift_card, notice: 'Gift card was successfully created.' }
        format.json { render json: @gift_card, status: :created, location: @gift_card }
      else
        format.html { render action: "new" }
        format.json { render json: @gift_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gift_cards/1
  # PUT /gift_cards/1.json
  def update
    @gift_card = GiftCard.find(params[:id])

    respond_to do |format|
      if @gift_card.update_attributes(params[:gift_card])
        format.html { redirect_to @gift_card, notice: 'Gift card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gift_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gift_cards/1
  # DELETE /gift_cards/1.json
  def destroy
    @gift_card = GiftCard.find(params[:id])
    @gift_card.destroy

    respond_to do |format|
      format.html { redirect_to gift_cards_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports/gift_cards
  # GET /reports/gift_cards.json
  def gift_cards
    @report = GiftCard.report

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @report }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gift_cards_helper.rb
module GiftCardsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/gift_cards/_form.html.erb
<%= form_for(@gift_card) do |f| %>
  <% if @gift_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift_card.errors.count, "error") %> prohibited this gift_card from being saved:</h2>

      <ul>
      <% @gift_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender %><br />
    <%= f.text_field :sender %>
  </div>
  <div class="field">
    <%= f.label :receiver %><br />
    <%= f.text_field :receiver %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gift_cards/edit.html.erb
<h1>Editing gift_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift_card %> |
<%= link_to 'Back', gift_cards_path %>

app/views/gift_cards/index.html.erb
<h1>Listing gift_cards</h1>

<table>
  <tr>
    <th>Sender</th>
    <th>Receiver</th>
    <th>Description</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gift_cards.each do |gift_card| %>
  <tr>
    <td><%= gift_card.sender %></td>
    <td><%= gift_card.receiver %></td>
    <td><%= gift_card.description %></td>
    <td><%= gift_card.value %></td>
    <td><%= link_to 'Show', gift_card %></td>
    <td><%= link_to 'Edit', edit_gift_card_path(gift_card) %></td>
    <td><%= link_to 'Destroy', gift_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gift card', new_gift_card_path %> |
<%= link_to 'Home', '/' %>

app/views/gift_cards/new.html.erb
<h1>New gift_card</h1>

<%= render 'form' %>

<%= link_to 'Back', gift_cards_path %>

app/views/gift_cards/report.html.erb
<h1>Reporting gift_cards</h1>

<table>
  <tr>
    <th>Sender</th>
    <th>Gifts given</th>
    <th>Spent</th>
  </tr>

<% @report.keys.each do |sender_name| %>
  <tr>
    <td><%= sender_name %></td>
    <td><%= @report[sender_name][:gifts_given] %></td>
    <td><%= @report[sender_name][:spent] %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', gift_cards_path %>

app/views/gift_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sender:</b>
  <%= @gift_card.sender %>
</p>

<p>
  <b>Receiver:</b>
  <%= @gift_card.receiver %>
</p>

<p>
  <b>Description:</b>
  <%= @gift_card.description %>
</p>

<p>
  <b>Value:</b>
  <%= @gift_card.value %>
</p>


<%= link_to 'Edit', edit_gift_card_path(@gift_card) %> |
<%= link_to 'Back', gift_cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GiftCardsChallenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/gift_cards.html.erb
<h1>Reporting Gift Cards</h1>

<table>
  <tr>
    <th>Sender</th>
    <th>Gifts given</th>
    <th>Spent</th>
  </tr>

<% @report.keys.each do |sender_name| %>
  <tr>
    <td><%= sender_name %></td>
    <td><%= @report[sender_name][:gifts_given] %></td>
    <td><%= @report[sender_name][:spent] %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Home', '/' %>